config/routes.rb
Rails.application.routes.draw do
  namespace :login do
    get 'dasboard/index'
  end
  namespace :site do
    get 'users/index'
    resources :users
    get 'welcome/index'
    post 'welcome/index'
    #get 'welcome/destroy', only: [:destroy]
    delete 'welcome/destroy'
    get 'search', to: 'search#users'
  end

  namespace :login do
    get 'welcome/index'
    post 'welcome/index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'login/welcome#index' 
  
  #root to: 'login/dasboard#index'
  
  get '/inicio' , to: 'login/welcome#index'
  get '/contra-cheque', to: 'site/welcome#index'

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/site/search_controller.rb
class Site::SearchController < ApplicationController
  def users
    @users = User.where("acesso LIKE ?","%#{params[:term]}%")
             .page(params[:page])
  
  end
end

app/controllers/site/users_controller.rb
class Site::UsersController < ApplicationController
  http_basic_authenticate_with name: "@Pintos", password: "@PINTOS2020@@", only: [:index]
  before_action :verify_password, only:[:update]
  before_action :set_user , only: [:show, :edit, :update, :destroy]
  
  def index 
    @users = User.all.page(params[:page]).per(25).order(:acesso)
    #@q = User.ransack(params[:q])
    #@users = @q.result(distinct: true)
  end

  def show
  end

  def edit
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save()
      redirect_to site_users_index_path, notice: "Usuário Criado com Sucesso !"
    else
      render :new
    end
   
  end


  def update

    if @user.update(params_user)
    redirect_to site_welcome_index_path, notice: "Usuário Atualizado com Sucesso !"
    else
    render :edit
    end
 
  end


  def search
    
    #@q = User.ransack(params[:q])
    #@users = @q.result(distinct: true)

    #@users = User.all
    #@users = User.includes(:users)
    #.where("lower(acesso,chapa) LIKE ?",
    #"%#{params[:term].downcase}%")
    #.page(params[:page])
    

  end

 private

 def verify_password 
   if params[:user][:password].blank? && params[:user].blank?
    params[:user].extract!(:password)
   end 
 end

 def set_user
  @user = User.find(params[:id])
 end
 
 def params_user
   params.require(:user).permit(:chapa,:password,:acesso)
 end

end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < ApplicationController
require 'base64'
  
  def index

    @users = User.where(acesso: "#{session[:username]}")

    @users.detect do |user|
      session[:username] == user.acesso  
       @user = user
       puts "#{user.chapa}"
    end
     
      if params[:commit].to_s == "Enviar"
       enviarDados(params[:mes],params[:ano]) 
        request[:ano] = params[:ano]
        request[:mes] = params[:mes]
      else
       flash[:info] = "Código/Usuário: #{session[:username]} , 
       na inatividade de 10 Minutos, será necessário renovar a sessão !" 
      end
       
  end
  
  def destroy
    params[:username] = nil
    params[:password] = nil
    reset_session
    redirect_to root_path  
    flash[:notice] = 'Agradecemos sua Visita!'   
  end
 
  def enviarDados(ano,mes)
  
    client = Savon.client(
      :wsdl => 'http://187.125.24.178:8052/wsReport/MEX?wsdl',
      :endpoint => 'http://187.125.24.178:8052/wsReport/IwsReport',
      :namespace => 'http://www.totvs.com/',
      basic_auth:["4456","040113"],
      headers: {
        "Authorization" => 'Basic NDQ1NjowNDAxMTM=', 
        "Connection" => 'Keep-Alive', 
        "Accept-Encoding" => "gzip,deflate", 
        "Content-Type" => "text/xml;charset=utf-8",
      },
      element_form_default: :qualified,
      :log => true,
      :pretty_print_xml => true,
      ssl_verify_mode: :none,
      log_level: :debug, 
      :raise_errors => true,
    )
  
     #client.operations
  
    message = {
      "codColigada" => '1',
      "id" => '194',
      "filters" =>'<?xml version="1.0" encoding="utf-16"?>
      <ArrayOfRptFilterReportPar xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.totvs.com.br/RM/">
        <RptFilterReportPar>
          <BandName>RptReport</BandName>
          <FiltersByTable />
          <MainFilter>true</MainFilter>
          <Value></Value>
        </RptFilterReportPar>
      </ArrayOfRptFilterReportPar>',
      "parameters" => '<?xml version="1.0" encoding="utf-16"?>
      <ArrayOfRptParameterReportPar xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.totvs.com.br/RM/">
        <RptParameterReportPar>
          <Description></Description>
          <ParamName>CHAPA</ParamName>
          <Type xmlns:d3p1="http://schemas.datacontract.org/2004/07/System" xmlns:d3p2="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.RuntimeType" i:type="d3p2:RuntimeType" xmlns:d3p3="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.UnitySerializationHolder" z:FactoryType="d3p3:UnitySerializationHolder" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
            <Data xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">System.String</Data>
            <UnityType xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int" xmlns="">4</UnityType>
            <AssemblyName xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</AssemblyName>
          </Type>
          <Value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">'+@user.chapa+'</Value>
          <Visible>true</Visible>
        </RptParameterReportPar>
        <RptParameterReportPar>
          <Description></Description>
          <ParamName>CODCOLIGADA</ParamName>
          <Type xmlns:d3p1="http://schemas.datacontract.org/2004/07/System" xmlns:d3p2="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.RuntimeType" i:type="d3p2:RuntimeType" xmlns:d3p3="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.UnitySerializationHolder" z:FactoryType="d3p3:UnitySerializationHolder" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
            <Data xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">System.String</Data>
            <UnityType xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int" xmlns="">4</UnityType>
            <AssemblyName xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</AssemblyName>
          </Type>
          <Value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">1</Value>
          <Visible>true</Visible>
        </RptParameterReportPar>
        <RptParameterReportPar>
          <Description></Description>
          <ParamName>NROPERIODO</ParamName>
          <Type xmlns:d3p1="http://schemas.datacontract.org/2004/07/System" xmlns:d3p2="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.RuntimeType" i:type="d3p2:RuntimeType" xmlns:d3p3="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.UnitySerializationHolder" z:FactoryType="d3p3:UnitySerializationHolder" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
            <Data xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">System.String</Data>
            <UnityType xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int" xmlns="">4</UnityType>
            <AssemblyName xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</AssemblyName>
          </Type>
          <Value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">2</Value>
          <Visible>true</Visible>
        </RptParameterReportPar>
        <RptParameterReportPar>
          <Description></Description>
          <ParamName>MESCOMP</ParamName>
          <Type xmlns:d3p1="http://schemas.datacontract.org/2004/07/System" xmlns:d3p2="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.RuntimeType" i:type="d3p2:RuntimeType" xmlns:d3p3="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.UnitySerializationHolder" z:FactoryType="d3p3:UnitySerializationHolder" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
            <Data xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">System.String</Data>
            <UnityType xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int" xmlns="">4</UnityType>
            <AssemblyName xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</AssemblyName>
          </Type>
          <Value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">'+request[:mes]+'</Value>
          <Visible>true</Visible>
        </RptParameterReportPar>
        <RptParameterReportPar>
          <Description></Description>
          <ParamName>ANOCOMP</ParamName>
          <Type xmlns:d3p1="http://schemas.datacontract.org/2004/07/System" xmlns:d3p2="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.RuntimeType" i:type="d3p2:RuntimeType" xmlns:d3p3="-mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089-System-System.UnitySerializationHolder" z:FactoryType="d3p3:UnitySerializationHolder" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
            <Data xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">System.String</Data>
            <UnityType xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:int" xmlns="">4</UnityType>
            <AssemblyName xmlns:d4p1="http://www.w3.org/2001/XMLSchema" i:type="d4p1:string" xmlns="">mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</AssemblyName>
          </Type>
          <Value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">'+request[:ano]+'</Value>
          <Visible>true</Visible>
        </RptParameterReportPar>
      </ArrayOfRptParameterReportPar>',
      "fileName" => 'report.pdf',
  }
  
  response = client.call(
      :generate_report,
      message: message
      
  )
  
  #p response.soap_fault?
  
  result_one = response.body[:generate_report_response][:generate_report_result]

  size(result_one)
  
  #doc = Nokogiri::Slop(result)
  
  #@result = doc.NewDataSet.Resultado

  rescue Exception => e 
   
  e.message


  end


  def size(result_one)

    client = Savon.client(
     :wsdl => 'http://187.125.24.178:8052/wsReport/MEX?wsdl',
     :endpoint => 'http://187.125.24.178:8052/wsReport/IwsReport',
     :namespace => 'http://www.totvs.com/',
     basic_auth:["4456","040113"],
     headers: {
        "Authorization" => 'Basic NDQ1NjowNDAxMTM=', 
        "Connection" => 'Keep-Alive' , 
        "Accept-Encoding" => "gzip,deflate", 
        "Content-Type" => "text/xml;charset=utf-8",
      },
      element_form_default: :qualified,
      :log => true,
      :pretty_print_xml => true,
      ssl_verify_mode: :none,
      log_level: :debug, 
      :raise_errors => true,
    )
  
     #client.operations
  
    message = {
      'guid' => "#{result_one}",
  }
  
  response = client.call(
      :get_generated_report_size,
      message: message
      
  )
  
  #p response.soap_fault?
  
  result_two = response.body[:get_generated_report_size_response][:get_generated_report_size_result]
  
  chunk(result_one,result_two)
  
  #.Base64.encode64(results)

  
  
  end

  def chunk(result_one,result_two)

    client = Savon.client(
      :wsdl => 'http://187.125.24.178:8052/wsReport/MEX?wsdl',
      :endpoint => 'http://187.125.24.178:8052/wsReport/IwsReport',
      :namespace => 'http://www.totvs.com/',
      basic_auth:["4456","040113"],
      headers: {
        "Authorization" => 'Basic NDQ1NjowNDAxMTM=', 
        "Connection" => 'Keep-Alive' , 
        "Accept-Encoding" => "gzip,deflate", 
        "Content-Type" => "text/xml;charset=utf-8",
      },

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/users_helper.rb
module Site::UsersHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/views/site/users/edit.html.erb
<%= render partial: 'site/users/shared/form' , locals: { action_message: 'Editando Usuário'}%>

app/views/site/users/index.html.erb
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    
    <title>Pintos LTDA </title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="#">Pintos LTDA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          

 
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Contra-Cheque", site_welcome_index_path, class: "nav-link" %>
                </li>
            </ul>

             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%=  link_to "Incluir Usuário", new_site_user_path, class: "nav-link" %> 
                </li>
            </ul>
       

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Sair", site_welcome_destroy_path(params[:username],params[:password]), method: :delete, data: { confirm: 'Tem Certeza?' }, class: "nav-link" %>
                </li>
            </ul>

        </div>
    </div>
</nav>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-lg">
                <div class="card">
                    <div class="card-header">Dados dos Usuários </div>
                    <div class="card-body">
                        
                             <div class="row-center">

                             <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                    <strong><%= flash_message %>  </strong> 
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>

                                     <%= form_with(url: site_search_path ,local: true, method: :get, class: 'form-group') do |form| %>

                                     
                                        <%= form.text_field :term , placeholder: 'Informe o código de acesso , para consulta ... ', class: 'form-control'%> 
                                        
                                        <%= form.submit "Pesquisar", class: 'btn btn-primary'%>
                                        <% end %>

                                  

                                 <table class="table table-bordered">
                                      <thead>
                                        <tr>
                                          <th scope="col">ID</th>
                                          <th scope="col">ACESSO</th>
                                          <th scope="col">CHAPA</th>
                                          <th scope="col">PASSWORD</th>
                                          <th scope="col">Ações</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                       <% @users.each do |user|%>
                                        <tr>
                                          <th scope="row"><%= user.id %></th>
                                          <td> <%= user.acesso %></td>
                                          <td><%= user.chapa %></td>
                                          <td>  <%#= user.password%></td>
                                          <td style="width: 100px">
                                          <%= link_to 'editar' ,edit_site_user_path(user), class:"btn btn-primary btn-circle" %>
                                             <i class="fa fa-edit"></i>
                                            <%# end %>
                                          </td>
                                        </tr>
                                      </tbody>
                                      <% end %>
                                    </table>
                                    <p class="text-center"> <%= paginate @users %>  </p>
                                </div>
                          </div>
                     </div>
                 </div>
             </div>
</main>
   
</body>
</html>

app/views/site/users/new.html.erb
<%= render partial: 'site/users/shared/form_new' , locals: { action_message: 'Incluindo Novo Usuário'}%>

app/views/site/users/show.html.erb
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
     

    <link rel="icon" href="Favicon.png">


    <title>Painel Administrativo</title>
</head>
<body>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><strong> <h3> Listando Usuários </h3> </strong>  </div>
                    <div class="card-body">
                          <div class="alert alert-success alert-dismissible fade show" role="alert" id="notice">
                              <strong> <%= notice %> </strong>
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <div class="table-responsive">
                                       <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                          <tr>
                                           <th>#</th>
                                           <th>Acesso</th>
                                           <th>Chapa</th>
                                           <th>Senha</th>
                                           <td style="width: 100px">
                                          <%= link_to new_site_user_path, class:"btn btn-success btn-circle" do %>
                                          <i class="fa fa-plus"></i>
                                          <% end %>
                                          </td>
                                         </tr>
                                       </thead>
                                         <tbody>
                                         <%# @users.each do |user| %>
                                          <tr>
                                          <td><%= @user.id %></td>
                                          <td><%= @user.acesso %></td>
                                          <td><%= @user.chapa %></td>
                                          <td><%= @user.password %></td>
                                          <td style="width: 100px">
                                          <%= link_to site_users_path(@user), class:"btn btn-primary btn-circle" do %>
                                             <i class="fa fa-mail-reply"></i>
                                            <% end %>
                                          </td>
                                          <td style="width: 100px">
                                          <%= link_to edit_site_user_path(user), class: "btn btn-warning btn-circle" do %>
                                          <i class="fa fa-minus"></i>
                                          <% end %>
                                          </td>
                                          
                                          </tr>
                                          <%# end %>
                                          </tbody>
                                          </table>
                                            
                                             <%#= paginate @users, class: 'text-center' %>
                                           
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

   
</main>

 





</body>
</html>